version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: churn-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: churn-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/churnDB
      - AI_SERVICE_URL=http://ai:8000
    depends_on:
      - mongo
      - ai

  ai:
    build: ./ai
    container_name: churn-ai
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  mongo:
    image: mongo:7
    container_name: churn-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
